name: Changesets

on:
    push:
        branches:
            - main
        paths:
            - '.changeset/**'
            - 'packages/**'
            - 'apps/**'
            - 'package.json'
            - 'turbo.json'
            - '.github/workflows/changesets.yml'

jobs:
    version:
        name: Version and Changelog
        runs-on: ubuntu-latest
        if: github.repository == 'monsoft-solutions/vernisai-website'

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Create Release Pull Request or Publish
              id: changesets
              uses: changesets/action@v1
              with:
                  version: npm run version
                  publish: npm run release
                  commit: 'chore: version packages'
                  title: 'chore: version packages'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Update Changes Directory
              if: steps.changesets.outputs.published == 'true'
              run: |
                  DATE=$(date +%Y-%m-%d)
                  CHANGES_FILE="changes/$DATE.md"

                  if [ ! -f "$CHANGES_FILE" ]; then
                    echo "Creating new changes file for $DATE"
                    touch "$CHANGES_FILE"
                  fi

                  echo -e "\n## Release $(date +%Y-%m-%d)" >> "$CHANGES_FILE"
                  echo -e "\n- Published new versions of packages" >> "$CHANGES_FILE"
                  echo -e "- Generated changelog from changesets" >> "$CHANGES_FILE"

                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git add "$CHANGES_FILE"
                  git commit -m "docs: update changes file for release"
                  git push
